# Generated by Django 6.0.2 on 2026-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_costs',
            new_name='unit_cost',
        ),
    ]
