# Generated by Django 6.0.2 on 2026-02-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_unit_costs_product_unit_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchase_price',
            new_name='unit_cost',
        ),
    ]
