# Generated by Django 6.0.2 on 2026-02-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_purchase_price_purchaseitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
