# Generated by Django 6.0.2 on 2026-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12),
            preserve_default=False,
        ),
    ]
