# Generated by Django 6.0.2 on 2026-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
