# Generated by Django 6.0.2 on 2026-02-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
