# Generated by Django 6.0.2 on 2026-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_price_orderitem_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
